//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int IdPedido { get; set; }
        public Nullable<int> CodigoProducto { get; set; }
        public System.DateTime FechaPedido { get; set; }
        public int CantidadPedido { get; set; }
        public decimal PrecioUnidad { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public string PersonaEntrega { get; set; }
        public string Empresa { get; set; }
        public string PersonaRecibe { get; set; }
        public string NumeroFactura { get; set; }
    
        public virtual Suministros Suministros { get; set; }
    }
}
