//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retiros
    {
        public int NumeroSolicitud { get; set; }
        public Nullable<int> CodigoProducto { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public int CantidadRetiro { get; set; }
        public string NombreCompleto { get; set; }
    
        public virtual Suministros Suministros { get; set; }
    }
}
